use_frameworks!
target 'HaierSweepRobotApp' do 
pod 'AFNetworking'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'JSONKit'
pod 'MBProgressHUD'
pod 'IQKeyboardManager', '~> 4.0.4'
pod 'MJExtension'
pod 'Masonry'
pod 'ReactiveCocoa', '~> 2.5'
pod 'BlocksKit'
pod 'JKCategories'
# U-Share SDK UI模块（分享面板，建议添加）
pod 'UMengUShare/UI'
# 集成新浪微博
pod 'UMengUShare/Social/Sina'
# 集成微信
pod 'UMengUShare/Social/WeChat'
# 集成QQ
pod 'UMengUShare/Social/QQ'

end
